import img1 from "../../assets/dealsImg1.jpg";
import img2 from "../../assets/dealsImg2.jpg";
import img3 from "../../assets/dealsImg3.jpg";
import img4 from "../../assets/dealsImg4.jpg";
import img5 from "../../assets/dealsImg5.jpg";
import img6 from "../../assets/dealsImg6.jpg";
import img7 from "../../assets/dealsImg7.jpg";
import img8 from "../../assets/dealsImg8.jpg";
import img9 from "../../assets/dealsImg9.jpg";
import img10 from "../../assets/dealsImg10.jpg";
import img11 from "../../assets/dealsImg11.jpg";
import img12 from "../../assets/dealsImg12.jpg";
import img13 from "../../assets/dealsImg13.jpg";
import img14 from "../../assets/dealsImg14.jpg";
import subImg1 from '../../assets/subdeals1.png';
import subImg2 from '../../assets/subdeals2.png';
import subImg3 from '../../assets/subdeals3.png';
import subImg4 from '../../assets/subdeals4.png';
import subImg5 from '../../assets/subdeals5.png';
import roomImg from '../../assets/roomImg.png';
import wifi from '../../assets/wifi.png';
import room from '../../assets/room.png';
import area from '../../assets/area.png';
import direction from '../../assets/directions.png';
import smoking from '../../assets/smoking.png';

export const data = [
    {
      id: 1,
      img: img1,
      subdealimg1: subImg1,
      subdealimg2: subImg2,
      subdealimg3: subImg3,
      subdealimg4: subImg4,
      subdealimg5: subImg5,
      title: "Eid Offer Armenia, Tashkent and Bishkek",
      button: 'Getaway Deal',
      location: "Armenia, Tashkent and Bishkek",
      locationDistance: "(1.9 km from centre)",
      travel: "Travel to Armenia, Tashkent and Bishkek in Eid holidays",
      travelDiscription: "3 nights 4 days",
      benifits: "Full package with flight and hotel",
      num: "056 6696251",
      web: "www.deals4trip.com",
      star: 5,
      rating: 8.8,
      map: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      persons: "No Size Limit",
      chargesBefore: "$14,715",
      chargesNow: "$148.25",
      chargesDescription: "+$ 3,407 taxes and charges",
      availability: '/link',
      overview: "You can directly book the best price if your travel dates are available, all discounts are already included. In the following house description you will find all information about our listing.\n\n2-room terraced house on 2 levels. Comfortable and cosy furnishings: 1 room with 1 french bed and radio. Shower, sep. WC. Upper floor: (steep stair) living/dining room with 1 sofabed (110 cm, length 180 cm), TV. Exit to the balcony. Small kitchen (2 hot plates, oven,). You can directly book the best price if your travel dates are available, all discounts are already included. In the following house description you will find all information about our listing.\n\n2-room terraced house on 2 levels. Comfortable and cosy furnishings: 1 room with 1 french bed and radio. Shower, sep. WC. Upper floor: (steep stair) living/dining room with 1 sofabed (110 cm, length 180 cm), TV. Exit to the balcony. Small kitchen (2 hot plates, oven,). You can directly book the best price if your travel dates are available, all discounts are already included. In the following house description you will find all information about our listing.\n\n2-room terraced house on 2 levels. Comfortable and cosy furnishings: 1 room with 1 french bed and radio. Shower, sep. WC. Upper floor: (steep stair) living/dining room with 1 sofabed (110 cm, length 180 cm), TV. Exit to the balcony. Small kitchen (2 hot plates, oven,).",
      roomType: 'Bliss Suite (1 bedroom)',
      roomImg: roomImg,
      wifi: wifi,
      isWiFi: 'Free WiFi',
      room: room,
      roomName: 'King Room',
      area: area,
      areaFt: '22Ft',
      smoking: smoking,
      direction: direction,
      directionView: 'City View',
      isSmoking: 'Non-smoking rooms',
      price: 'AED 72',
      priceDescription: 'Includes taxes and charges'
    },
    {
      id: 2,
      img: img2,
      subdealimg: subImg2,
      title: "EID OFFERS",
      button: 'Getaway Deal',
      location: "Baku and Georgia",
      travel: "Travel to Baku and Georgia in Eid holidays",
      travelDiscription: "3 nights 4 days",
      benifits: "Full package with flight and hotel",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "$ 14,715",
      chargesNow: "$148.25",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
    {
      id: 3,
      img: img3,
      subdealimg: subImg3,
      title: "EID OFFERS",
      button: 'Getaway Deal',
      location: "Almaty",
      travel: "Travel to Almaty in Eid holidays",
      travelDiscription: "3 nights 4 days",
      benifits: "Full package with flight and hotel",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "",
      chargesNow: "Per person 3349 AED",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
    {
      id: 4,
      img: img4,
      subdealimg: subImg4,
      title: "Best discounts on: Hotel staycation",
      button: 'Getaway Deal',
      location: "Hotel staycation",
      travel: "Excursions and attractions in UAE Best Desert safari tours Yacht trips Travel packages And much more",
      travelDiscription: "3 nights 4 days",
      benifits: "We can assist and provide best rates for any place you wish to visit.",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "$ 14,715",
      chargesNow: "$148.25",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
    {
      id: 5,
      img: img5,
      subdealimg: subImg5,
      title: "Dive into the Beauty of Maldives",
      button: 'Getaway Deal',
      location: "Maldives",
      travel: "Discover the Ultimate Tropical Getaway in the Maldives!",
      travelDiscription: "3 nights 4 days",
      benifits: "Our dedicated team is ready to assist you every step of the way, from crafting the perfect itinerary to arranging seamless travel logistics.",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "$ 14,715",
      chargesNow: "$148.25",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
    {
      id: 6,
      img: img6,
      title: "Travel to DESERT SAFARI",
      button: 'Getaway Deal',
      location: "Desert Safari",
      travel: "Enjoy with us best Desert safari tour With VIP camps, dune bashing, buffet and all activities.",
      travelDiscription: "3 nights 4 days",
      benifits: "Full package with flight and hotel",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "$ 14,715",
      chargesNow: "$148.25",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
    {
      id: 7,
      img: img7,
      title: "Enjoy Arabian deserts",
      button: 'Getaway Deal',
      location: "Arabian desert",
      travel: "Enjoy Arabian deserts with Red dunes and premium camps with our trained team to make tour trip memorable.",
      travelDiscription: "3 nights 4 days",
      benifits: "Full package with flight and hotel",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "$ 14,715",
      chargesNow: "$148.25",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
    {
      id: 8,
      img: img8,
      title: "COVE ROTANA RAK",
      button: 'Getaway Deal',
      location: "Cove Rotana",
      travel: "Best resort on the beaches of RAK with amazing discounts.",
      travelDiscription: "1 night",
      benifits: "Full package with flight and hotel",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "",
      chargesNow: "1150 AED per night",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
    {
      id: 9,
      img: img9,
      title: "Yas Island Parks with Hotels",
      button: 'Getaway Deal',
      location: "Yas Island",
      travel: "Best offers available for Abu dhabi hotels and Yas Island hotels with Park access:",
      travelDiscription: "1 night with 1 or 2 park access",
      benifits: "Ferrari world, Warner bros, SeaWorld, Yas waterworld",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "$ 14,715",
      chargesNow: "$148.25",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
    {
      id: 10,
      img: img10,
      title: "Enjoy Arabian Deserts With Red Dunes",
      button: 'Getaway Deal',
      location: "Arabian deserts with Red dunes",
      travel: "Enjoy Arabian deserts with Red dunes and premium camps with our trained team to make tour trip memorable.",
      travelDiscription: "1 night stay",
      benifits: "",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "$ 14,715",
      chargesNow: "$148.25",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
    {
      id: 11,
      img: img11,
      title: "Museum Of Future",
      button: 'Getaway Deal',
      location: "Museum of future",
      travel: "",
      travelDiscription: "1 days",
      benifits: "",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "$ 14,715",
      chargesNow: "$148.25",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
    {
      id: 12,
      img: img12,
      title: "ENJOY AZERBAİJAN GEORGIA TRIP WITH REASONABLE RATES",
      button: 'Getaway Deal',
      location: "Azerbaijan Georgia",
      travel: "ENJOY AZERBAİJAN + GEORGIA TRIP WITH REASONABLE RATES",
      travelDiscription: " 8 nights, 9 days",
      benifits: "4 nights in Tbilisi 3, 4 nights in Baku 4, All tours and tranfers during tour on PVT basis, Airport transfers, Tbilisi tour, Gudauri, Kazbegi, Kakethi tour, Baku tour",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "",
      chargesNow: "AED 1950 Per Person",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
    {
      id: 13,
      img: img13,
      title: "GOA TRIP",
      button: 'Getaway Deal',
      location: "GOA",
      travel: "UAE national day offer inclusive of Flight and Stay at Taj Goa",
      travelDiscription: "4 nights",
      benifits: "",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "$ 14,715",
      chargesNow: "$148.25",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
    {
      id: 14,
      img: img14,
      title: "ABU DHABI GRAND PRIX",
      button: 'Getaway Deal',
      location: "Abu Dhabi",
      travel: "Grab the remaining tickets with discounts",
      travelDiscription: "1 days",
      benifits: "Available Tickets Slots – Northern GrandStand -AED 2400 for 3 Days per ticket price( 06 TICKET AVAILABLE ) MAIN GRANDSTAND PREMIUM – AED 5500/- for 3 days per ticket price ( 2 TICKET AVAILABLE)",
      num: "056 6696251",
      web: "www.deals4trip.com",
      persons: "No Size Limit",
      locationDistance: "(1.9 km from centre)",
      star: 5,
      rating: 4.8,
      map: '/link',
      availability: '/link',
      ratingDescription: "Exceptional 3,014 reviews",
      chargesBefore: "$ 14,715",
      chargesNow: "$148.25",
      chargesDescription: "+$ 3,407 taxes and charges",
    },
  ];
